scrape_configs:
  - job_name: 'ecs'
    ec2_sd_configs:
      - region: 'us-east-1'
        access_key: 'YOUR_AWS_ACCESS_KEY'
        secret_key: 'YOUR_AWS_SECRET_KEY'
    relabel_configs:
      - source_labels: [__meta_ec2_instance_id]
        target_label: 'instance'
