name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t spring-boot-app .
        
      - name: Tag Docker image
        run: |
          docker tag spring-boot-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/spring-boot-app:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/spring-boot-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Update ECS Task Definition
        run: |
          aws ecs register-task-definition \
            --family spring-boot-app-task \
            --container-definitions file://container_definitions.json

      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster ecs-cluster \
            --service spring-boot-app-service \
            --task-definition spring-boot-app-task
